# Generated by Django 5.0.4 on 2024-05-20 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=200)),
                ('duration', models.DurationField()),
                ('start', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.IntegerField()),
                ('weekly', models.FloatField()),
                ('taskName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.task')),
            ],
        ),
    ]
