# Generated by Django 5.0.4 on 2024-05-24 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0004_alter_task_id_alter_task_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 13, 39, 41, 697099)),
        ),
    ]
