# Generated by Django 5.0.4 on 2024-05-27 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0005_alter_task_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 12, 53, 40, 897827)),
        ),
    ]
