# Generated by Django 5.0.4 on 2024-05-28 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0006_alter_task_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taskName',
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.CharField(choices=[('Top', 'top'), ('Low', 'low'), ('Mid', 'mid')], default='Mid', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='mid', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
