# Generated by Django 5.0.4 on 2024-05-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0007_remove_task_taskname_task_task_id_task_task_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(choices=[('Top', 'top'), ('Low', 'low'), ('Mid', 'mid')], default='mid', max_length=20),
        ),
    ]
