# Generated by Django 5.0.4 on 2024-05-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0009_alter_task_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
